language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.7

matrix:
  include:
   - os: linux
    name: Integration install
    python: 3.7
    install:
    - python setup.py install
    - pip install mozloc[tests,full]
    script:
    - cd $HOME
    - python -m pytest $TRAVIS_BUILD_DIR/tests -r a -v
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy .
